apiVersion: v1
kind: Service
metadata:
  name: contest-cpfed-frontend
spec:
  selector:
    app.kubernetes.io/name: contest-cpfed-frontend
  ports:
  - name: http
    protocol: TCP
    port: 31745
    targetPort: contest-cpfed-frontend-svc
  type: LoadBalancer
